### ISSUE TITLE
How to prioritize user stories

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/user-stories#8]
### User Profile

As a project owner

### User Action

I want to know how how to prioritize user stories

### User Goal

So that I can drive growth of key metrics for Pangeo Forge

### Acceptance Criteria

A process for linking user stories to key metrics we'd like to achieve for the platform, as described in [this tweet](https://twitter.com/lauraklein/status/1520908880179777536?s=20&t=h5D6-ESy7HiTe0PzvKgYEQ):

> 3. Is this the group of users whose needs we want to address right now? Why? Are we trying to improve a particular metric for that specific type of user? Are they particularly underserved by the product or important to our business or other goals?

**Comment by rabernat** [comment]
This is sort of a meta user story. 🤯 I'm not sure we can track it as a user story itself! But we should definitely be discussing it. We can discuss the framework today.
